project_id = "pdv-local-pro"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[auth]
site_url = "https://pdv-tico.vercel.app"
additional_redirect_urls = ["https://pdv-tico.vercel.app/**"]
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true

[inbucket]
enabled = true
port = 54324

[functions.process-payment]
enabled = true
verify_jwt = true
import_map = "./functions/process-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-payment/*.html" ]
